version: "3.7"
services:
    dev:
        image: "node:12.15-alpine"
        working_dir: "/srv"
        command: "npm run develop"
        tty: true
        volumes:
            - "./:/srv/"
        ports:
            - "8090:8080"
    build:
        image: "node:12.15-alpine"
        working_dir: "/srv"
        command: "npm run build"
        tty: true
        volumes:
            - "./:/srv/"

